[PROD][KAIZEN-0] Erstatter gson med jackson
navikt/modiapersonoversikt-skrivestotte pull request #131
Opened 2022-07-12 09:04 UTC by vildestefferud

2022-07-12 10:54 UTC, nutgaard requested changes
Ser at det logges `Could not get leader from http://localhost:4040` i preprod nå. Så vi må nok ta en nærmere titt på dette før det går ut til produksjon

2022-07-12 10:54 UTC, nutgaard commented on src/main/kotlin/no/nav/modiapersonoversikt/skrivestotte/service/LeaderElectorService.kt
>              log.error("Could not get leader from ${configuration.electorPath}", e)
Denne ^^

2022-07-12 12:19 UTC, vildestefferud commented on src/main/kotlin/no/nav/modiapersonoversikt/skrivestotte/service/LeaderElectorService.kt
>              log.error("Could not get leader from ${configuration.electorPath}", e)
https://github.com/navikt/modiapersonoversikt-skrivestotte/pull/132 <- fix

2022-07-13 13:53 UTC, nutgaard approved these changes
:+1: Feilen ser ut til å ha forsvunnet fra loggene nå

2022-07-14 05:46 UTC, merged